services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: chewie_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-chewie_ai}
      POSTGRES_USER: ${POSTGRES_USER:-chewie}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-chewie}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chewie_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: chewie_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chewie_network
    restart: unless-stopped

  api:
    build: .
    container_name: chewie_api
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${API_EXTERNAL_PORT:-8000}:8000"
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE:-false}"
      - "traefik.http.routers.chewie-api.rule=Host(`${API_DOMAIN:-api.chewieai.com}`)"
      - "traefik.http.routers.chewie-api.entrypoints=websecure"
      - "traefik.http.routers.chewie-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.chewie-api.loadbalancer.server.port=8000"
    networks:
      - chewie_network
    restart: unless-stopped

  traefik:
    image: traefik:v2.10
    container_name: chewie_traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL:-admin@chewieai.com}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik_certs:/letsencrypt"
    networks:
      - chewie_network
    restart: unless-stopped
    profiles:
      - production  # Only start Traefik in production

volumes:
  postgres_data:
  redis_data:
  traefik_certs:

networks:
  chewie_network:
    driver: bridge
